Add error handling for cogs monthly booster
warnet-gi/WarnetBot pull request #124
Opened 2024-03-01 07:48 UTC by hilmoo

2024-03-01 07:54 UTC, Iqrar99 requested changes

2024-03-01 07:54 UTC, Iqrar99 commented on bot/cogs/booster.py
> +            if member_error != '':
Can be simplify to
```suggestion
            if member_error:
```

2024-03-01 07:54 UTC, Iqrar99 commented on bot/cogs/booster.py
> +                    title="Error handling user", description=member_error, colour=0xFF0000
Discord.color.red() would be better for clarity

2024-03-01 21:59 UTC, hilmoo commented
My latest update:
If an error occurs, the wrapper will return None, which will then be handled in booster.py. Also, now the log is inside wrapper.py.

2024-03-02 15:53 UTC, Iqrar99 requested changes

2024-03-02 15:53 UTC, Iqrar99 commented on bot/cogs/booster.py
> +    @tasks.loop(time=time(hour=4, minute=54, tzinfo=timezone(timedelta(hours=7))))
why?

2024-03-02 15:53 UTC, Iqrar99 commented on bot/cogs/booster.py
> +        if date.day == 2:
should be 1

2024-03-02 15:53 UTC, Iqrar99 commented on bot/cogs/booster.py
> +            succes_count = error_count = 0
```suggestion
            success_count = error_count = 0
```

2024-03-02 15:53 UTC, Iqrar99 commented on bot/cogs/booster.py
> +                if result is not None:
Can be refactored to
```suggestion
                if result:
```

2024-03-02 15:53 UTC, Iqrar99 commented on bot/cogs/booster.py
> +            print(succes_count)
remove debug lines

2024-03-02 15:53 UTC, Iqrar99 commented on bot/module/tatsu/wrapper.py
> +        if result is not None:
```suggestion
        if result:
```

2024-03-03 07:10 UTC, Iqrar99 approved these changes
LGTM

2024-03-03 07:13 UTC, merged